import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { readBalanceProfiles, readContent, readContentSchema, root, validateContent } from "./content-tools.mjs";

const content = readContent();
const schema = readContentSchema();
const balanceProfiles = readBalanceProfiles();
const errors = validateContent(content);
const compatibilityMirror = `${JSON.stringify(content, null, 2)}\n`;

if (errors.length) {
  console.error("# Tap Survivor Content Build");
  errors.forEach((error) => console.error(`FAIL ${error}`));
  process.exit(1);
}

const classicGenerated = [
  "// Generated by scripts/build-content.mjs. Edit content/registry/*.json and content/balance/*.json instead.",
  "// Retired global: TapSurvivorContent. Content is supplied through src/content.generated.mjs.",
  "",
].join("\n");

const moduleGenerated = [
  "// Generated by scripts/build-content.mjs. Edit content/registry/*.json and content/balance/*.json instead.",
  `export const content = ${JSON.stringify(content, null, 2)};`,
  `export const contentSchema = ${JSON.stringify(schema, null, 2)};`,
  `export const balanceProfiles = ${JSON.stringify(balanceProfiles, null, 2)};`,
  "",
].join("\n");

writeFileSync(join(root, "src/content.generated.js"), classicGenerated);
writeFileSync(join(root, "src/content.generated.mjs"), moduleGenerated);
if (!process.env.TAP_SURVIVOR_CONTENT_PATH) {
  writeFileSync(join(root, "content/tap-survivor-content.json"), compatibilityMirror);
  console.log("PASS wrote content/tap-survivor-content.json");
} else {
  console.log("SKIP content/tap-survivor-content.json for TAP_SURVIVOR_CONTENT_PATH override");
}

console.log("# Tap Survivor Content Build");
console.log("PASS wrote src/content.generated.js");
console.log("PASS wrote src/content.generated.mjs");
