import { readFileSync } from "node:fs";
import { join } from "node:path";
import { readContent, readContentSchema, root, validateContent } from "./content-tools.mjs";

const content = readContent();
const schema = readContentSchema();
const errors = validateContent(content);
const generatedPath = join(root, "src/content.generated.js");
const expected = `// Generated by scripts/build-content.mjs. Edit content/registry/*.json and content/balance/*.json instead.\nglobalThis.TapSurvivorContent = ${JSON.stringify(content, null, 2)};\nglobalThis.TapSurvivorContentSchema = ${JSON.stringify(schema, null, 2)};\n`;
const actual = readFileSync(generatedPath, "utf8");

console.log("# Tap Survivor Content Check");

if (errors.length) {
  errors.forEach((error) => console.error(`FAIL ${error}`));
  process.exit(1);
}
console.log("PASS content registry validates");

if (actual !== expected) {
  console.error("FAIL src/content.generated.js is stale or hand-edited. Run `npm run build:content`.");
  process.exit(1);
}
console.log("PASS generated content matches registry");
