import { readFileSync } from "node:fs";
import { join } from "node:path";
import { readBalanceProfiles, readContent, readContentSchema, root, validateContent } from "./content-tools.mjs";

const content = readContent();
const schema = readContentSchema();
const balanceProfiles = readBalanceProfiles();
const errors = validateContent(content);
const classicGeneratedPath = join(root, "src/content.generated.js");
const moduleGeneratedPath = join(root, "src/content.generated.mjs");
const expectedClassic = [
  "// Generated by scripts/build-content.mjs. Edit content/registry/*.json and content/balance/*.json instead.",
  "// Retired global: TapSurvivorContent. Content is supplied through src/content.generated.mjs.",
  "",
].join("\n");
const expectedModule = [
  "// Generated by scripts/build-content.mjs. Edit content/registry/*.json and content/balance/*.json instead.",
  `export const content = ${JSON.stringify(content, null, 2)};`,
  `export const contentSchema = ${JSON.stringify(schema, null, 2)};`,
  `export const balanceProfiles = ${JSON.stringify(balanceProfiles, null, 2)};`,
  "",
].join("\n");
const classicActual = readFileSync(classicGeneratedPath, "utf8");
const moduleActual = readFileSync(moduleGeneratedPath, "utf8");
const compatibilityMirrorPath = join(root, "content/tap-survivor-content.json");
const expectedCompatibilityMirror = `${JSON.stringify(content, null, 2)}\n`;

console.log("# Tap Survivor Content Check");

if (errors.length) {
  errors.forEach((error) => console.error(`FAIL ${error}`));
  process.exit(1);
}
console.log("PASS content registry validates");

if (!process.env.TAP_SURVIVOR_CONTENT_PATH) {
  const compatibilityMirrorActual = readFileSync(compatibilityMirrorPath, "utf8");
  if (compatibilityMirrorActual !== expectedCompatibilityMirror) {
    console.error("FAIL content/tap-survivor-content.json is stale. Run `npm run build:content`.");
    process.exit(1);
  }
  console.log("PASS compatibility mirror matches assembled registry content");
} else {
  console.log("SKIP compatibility mirror check for TAP_SURVIVOR_CONTENT_PATH override");
}

if (
  /\b(?:globalThis|window)\b/u.test(classicActual) ||
  classicActual.includes("Object.defineProperty") ||
  classicActual.includes("balanceProfiles") ||
  classicActual.includes("const content")
) {
  console.error(
    "FAIL src/content.generated.js must be a global-free compatibility artifact without content or profile payloads."
  );
  process.exit(1);
}
console.log("PASS classic generated content is global-free without content or profile payloads");

if (classicActual !== expectedClassic) {
  console.error("FAIL src/content.generated.js is stale or hand-edited. Run `npm run build:content`.");
  process.exit(1);
}
console.log("PASS classic generated content matches registry");

const requiredModuleExports = ["content", "contentSchema", "balanceProfiles"];
const missingModuleExports = requiredModuleExports.filter(
  (name) => !new RegExp(`\\bexport\\s+const\\s+${name}\\s*=`).test(moduleActual)
);
if (missingModuleExports.length) {
  console.error(
    `FAIL src/content.generated.mjs is missing required exports: ${missingModuleExports.join(", ")}.`
  );
  process.exit(1);
}
console.log("PASS generated ESM content exposes required named exports");

if (moduleActual !== expectedModule) {
  console.error("FAIL src/content.generated.mjs is stale or hand-edited. Run `npm run build:content`.");
  process.exit(1);
}
console.log("PASS generated ESM content matches registry");
