import { existsSync, readFileSync } from "node:fs";
import { readContent } from "./content-tools.mjs";

const domain = process.argv[2] || "help";
const content = readContent();
const files = new Map();
let failed = false;

function read(path) {
  if (!files.has(path)) files.set(path, existsSync(path) ? readFileSync(path, "utf8") : "");
  return files.get(path);
}

function check(name, pass) {
  console.log(`${pass ? "PASS" : "FAIL"} ${name}`);
  if (!pass) failed = true;
}

function usage() {
  console.log("Usage: node scripts/verify-focus.mjs <assets|audio|content|relics|ui>");
}

function verifyAssets() {
  const sprites = content.assets?.sprites || {};
  const spriteSheets = sprites.spriteSheets || {};
  check("asset resolver module is loaded", read("index.html").includes("src/assets.js") && read("src/assets.js").includes("createAssetResolver"));
  check("weapons have effect sprites and clean icons", Object.keys(content.weapons || {}).every((id) => sprites.weapons?.[id]?.src && sprites.weapons?.[id]?.iconSrc));
  check("run upgrades have effect sprites and clean icons", (content.runUpgrades || []).every((upgrade) => sprites.runUpgrades?.[upgrade.id]?.src && sprites.runUpgradeIcons?.[upgrade.id]));
  check(
    "split skill sprites are used",
    Object.values(sprites.weapons || {}).every((sprite) => sprite.src?.includes("skill-effects/split/skill-")) &&
      Object.values(sprites.runUpgrades || {}).every((sprite) => sprite.src?.includes("skill-effects/split/skill-")),
  );
  check("enemy and boss sprite sheets are registered", spriteSheets.enemies?.path?.includes("spritesheets/enemies-tower-pack.png") && spriteSheets.bosses?.path?.includes("spritesheets/bosses-tower-pack.png"));
}

function verifyAudio() {
  const audio = read("src/audio.js");
  const weaponFire = read("src/weapon-fire.js");
  check("all weapons have SFX", Object.keys(content.weapons || {}).every((id) => content.assets?.sfx?.weapons?.[id]));
  check("all run upgrades have SFX", (content.runUpgrades || []).every((upgrade) => content.assets?.sfx?.runUpgrades?.[upgrade.id]));
  check("weapon SFX scales with cooldown", audio.includes("playbackRate") && weaponFire.includes("weaponSfxOptions") && weaponFire.includes("weaponCooldown(weapon)"));
}

function verifyContent() {
  check("generated content warning exists", read("src/content.generated.js").startsWith("// Generated by scripts/build-content.mjs"));
  check("content check script exists", read("scripts/content-check.mjs").includes("generated content matches registry"));
  check("content registry includes core sections", ["weapons", "runUpgrades", "quests", "assets", "relics"].every((key) => content[key]));
}

function verifyRelics() {
  const shellUi = read("src/shell-ui.js");
  const shellRelicUi = read("src/shell-relic-ui.js");
  const combatDamage = read("src/combat-damage.js");
  const combat = read("src/combat.js");
  const weaponProjectiles = read("src/weapon-projectiles.js");
  const enemyBehaviors = read("src/enemy-behaviors.js");
  const pickups = read("src/pickups.js");
  const rendering = read("src/rendering.js");
  const relics = content.relics || [];
  const greenRelics = relics.filter((relic) => relic.rarity === "green");
  check("relics target existing run upgrades", (content.relics || []).every((relic) => (content.runUpgrades || []).some((upgrade) => upgrade.id === relic.targetUpgradeId)));
  check("relic inventory uses central icon resolver", shellRelicUi.includes("assetResolver.relicIcon"));
  check("locked relic popup exists", shellRelicUi.includes("Locked, play more to unlock this skill."));
  check(
    "generated random relic pool has no floor prefixes",
    relics.every((relic) => !/^floor_\d{3}_/.test(relic.id)),
  );
  check(
    "generated random relic tiers are present",
    relics.filter((relic) => /^random_/.test(relic.id)).length === 96 &&
      relics.filter((relic) => /_obsessed_relic$/.test(relic.id)).length === 32,
  );
  check(
    "relic named-upgrade spawn rates are tiered",
    relics.every((relic) => {
      const expectedMultiplier = { 1: 2, 2: 3, 3: 5 }[relic.startingTierBonus || relic.maxTierBonus];
      return !expectedMultiplier || relic.selectionWeightBonus === expectedMultiplier;
    }) &&
      read("src/level-up.js").includes("relicSpawnRateMultiplierFor") &&
      read("src/level-up.js").includes("relicSpawnRateMultiplier"),
  );
  check(
    "super boss relic extras fill the 100-item generated pool",
    relics.filter((relic) => /^super_boss_/.test(relic.id)).length === 4,
  );
  check(
    "every relic has a unique static icon",
    relics.every(
      (relic) =>
        relic.iconPath?.includes("assets/generated/tower/sprites/relics/") &&
        existsSync(relic.iconPath.split("?")[0]),
    ) && new Set(relics.map((relic) => relic.iconPath)).size === relics.length,
  );
  check(
    "twenty-six green relics have unique special abilities",
    greenRelics.length === 26 &&
      new Set(greenRelics.map((relic) => relic.specialAbility?.id)).size === 26 &&
      greenRelics.every((relic) => relic.backgroundColor && relic.specialAbility?.description),
  );
  check(
    "green relic names are based on their special effects",
    greenRelics.every((relic) => relic.name === `${relic.specialAbility.label} Relic`),
  );
  check(
    "green relic UI background is wired",
    shellRelicUi.includes("green-relic") && read("src/styles.css").includes(".green-relic"),
  );
  check(
    "green relic runtime effects are wired",
    combat.includes("damagePlayer") &&
      combatDamage.includes("lifestealOnKill") &&
      combatDamage.includes("killExplosionDamage") &&
      weaponProjectiles.includes("projectileSpeedBonus") &&
      weaponProjectiles.includes("doubleShotCount") &&
      enemyBehaviors.includes("damagePlayer?.") &&
      pickups.includes("coinMultiplier") &&
      rendering.includes("invincibleTimer"),
  );
}

function verifyUi() {
  const index = read("index.html");
  const styles = read("src/styles.css");
  const levelUp = read("src/level-up.js");
  check(
    "level-up uses static central choice icons",
    levelUp.includes("assetResolver.choiceIconPath") && !levelUp.includes("renderChoiceSprite"),
  );
  check(
    "level-up choices fit horizontally without modal scroll",
    styles.includes("height: min(80vh") &&
      styles.includes("#levelUp .choice-list") &&
      styles.includes("grid-template-columns: repeat(3, minmax(0, 1fr))") &&
      styles.includes("#levelUp .modal-box") &&
      styles.includes("overflow: hidden"),
  );
  check("inventory UI exists", index.includes('id="menuInventoryTab"') && index.includes('id="menuRelicInventory"'));
  check("index chrome is removed", !index.includes("<aside") && !index.includes("Tap Survivor MVP") && !index.includes('id="runHud"') && !index.includes('id="startRun"'));
  check("run menu tabs stay in one three-column row", styles.includes("grid-template-columns: repeat(3, minmax(0, 1fr))"));
  check("run menu keeps tabs visible while panels scroll", styles.includes("#runMenu .menu-box") && styles.includes("grid-template-rows: auto auto minmax(0, 1fr) auto") && styles.includes("#menuProgressPanel"));
  check("modal boxes remain scrollable", styles.includes("overflow-y: auto"));
}

const verifiers = {
  assets: verifyAssets,
  audio: verifyAudio,
  content: verifyContent,
  relics: verifyRelics,
  ui: verifyUi,
};

console.log(`# Tap Survivor Focus Verify: ${domain}`);
if (!verifiers[domain]) {
  usage();
  process.exit(domain === "help" ? 0 : 1);
}
verifiers[domain]();
if (failed) process.exit(1);
