import { existsSync, readFileSync } from "node:fs";

const domain = process.argv[2] || "help";
const content = readJson("content/tap-survivor-content.json");
const files = new Map();
let failed = false;

function read(path) {
  if (!files.has(path)) files.set(path, existsSync(path) ? readFileSync(path, "utf8") : "");
  return files.get(path);
}

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function check(name, pass) {
  console.log(`${pass ? "PASS" : "FAIL"} ${name}`);
  if (!pass) failed = true;
}

function usage() {
  console.log("Usage: node scripts/verify-focus.mjs <assets|audio|content|relics|ui>");
}

function verifyAssets() {
  const sprites = content.assets?.sprites || {};
  check("asset resolver module is loaded", read("index.html").includes("src/assets.js") && read("src/assets.js").includes("createAssetResolver"));
  check("weapons have effect sprites and clean icons", Object.keys(content.weapons || {}).every((id) => sprites.weapons?.[id]?.src && sprites.weapons?.[id]?.iconSrc));
  check("run upgrades have effect sprites and clean icons", (content.runUpgrades || []).every((upgrade) => sprites.runUpgrades?.[upgrade.id]?.src && sprites.runUpgradeIcons?.[upgrade.id]));
  check("split skill sprites are used", Object.values(sprites.weapons || {}).every((sprite) => sprite.src?.includes("skill-effects/split/skill-")) && Object.values(sprites.runUpgrades || {}).every((sprite) => sprite.src?.includes("skill-effects/split/skill-")));
}

function verifyAudio() {
  const audio = read("src/audio.js");
  const weaponFire = read("src/weapon-fire.js");
  check("all weapons have SFX", Object.keys(content.weapons || {}).every((id) => content.assets?.sfx?.weapons?.[id]));
  check("all run upgrades have SFX", (content.runUpgrades || []).every((upgrade) => content.assets?.sfx?.runUpgrades?.[upgrade.id]));
  check("weapon SFX scales with cooldown", audio.includes("playbackRate") && weaponFire.includes("weaponSfxOptions") && weaponFire.includes("weaponCooldown(weapon)"));
}

function verifyContent() {
  check("generated content warning exists", read("src/content.generated.js").startsWith("// Generated by scripts/build-content.mjs"));
  check("content check script exists", read("scripts/content-check.mjs").includes("generated content matches registry"));
  check("content registry includes core sections", ["weapons", "runUpgrades", "quests", "assets", "relics"].every((key) => content[key]));
}

function verifyRelics() {
  const shellUi = read("src/shell-ui.js");
  check("relics target existing run upgrades", (content.relics || []).every((relic) => (content.runUpgrades || []).some((upgrade) => upgrade.id === relic.targetUpgradeId)));
  check("relic inventory uses central icon resolver", shellUi.includes("assetResolver.relicIcon"));
  check("locked relic popup exists", shellUi.includes("Locked, play more to unlock this skill."));
}

function verifyUi() {
  const index = read("index.html");
  const levelUp = read("src/level-up.js");
  check("level-up uses central choice resolver", levelUp.includes("assetResolver.choiceIconDefinition") && levelUp.includes("assetResolver.choiceIconPath"));
  check("inventory UI exists", index.includes('id="menuInventoryTab"') && index.includes('id="menuRelicInventory"'));
  check("modal boxes remain scrollable", read("src/styles.css").includes("overflow-y: auto"));
}

const verifiers = {
  assets: verifyAssets,
  audio: verifyAudio,
  content: verifyContent,
  relics: verifyRelics,
  ui: verifyUi,
};

console.log(`# Tap Survivor Focus Verify: ${domain}`);
if (!verifiers[domain]) {
  usage();
  process.exit(domain === "help" ? 0 : 1);
}
verifiers[domain]();
if (failed) process.exit(1);
