(() => {
function createUi() {
  return {
    canvas: document.getElementById("game"),
    titleScreen: document.getElementById("titleScreen"),
    titleStartGame: document.getElementById("titleStartGame"),
    startTransition: document.getElementById("startTransition"),
    openShop: document.getElementById("openShop"),
    resetSave: document.getElementById("resetSave"),
    toggleDebug: document.getElementById("toggleDebug"),
    fullscreenButton: document.getElementById("fullscreenButton"),
    muteAudio: document.getElementById("muteAudio"),
    openMenu: document.getElementById("openMenu"),
    questBanner: document.getElementById("questBanner"),
    exitRun: document.getElementById("exitRun"),
    closeMenu: document.getElementById("closeMenu"),
    closeShop: document.getElementById("closeShop"),
    closeShopBottom: document.getElementById("closeShopBottom"),
    closeLevelUp: document.getElementById("closeLevelUp"),
    menuProgressTab: document.getElementById("menuProgressTab"),
    menuInventoryTab: document.getElementById("menuInventoryTab"),
    menuShopTab: document.getElementById("menuShopTab"),
    menuProgressPanel: document.getElementById("menuProgressPanel"),
    menuInventoryPanel: document.getElementById("menuInventoryPanel"),
    menuShopPanel: document.getElementById("menuShopPanel"),
    speedButtons: [...document.querySelectorAll("[data-speed]")],
    runMenu: document.getElementById("runMenu"),
    shopModal: document.getElementById("shopModal"),
    shopCoinHud: document.getElementById("shopCoinHud"),
    shopNotice: document.getElementById("shopNotice"),
    shopItems: document.getElementById("shopItems"),
    menuShopCoinHud: document.getElementById("menuShopCoinHud"),
    menuShopNotice: document.getElementById("menuShopNotice"),
    menuShopItems: document.getElementById("menuShopItems"),
    menuRelicSlots: document.getElementById("menuRelicSlots"),
    menuRelicInventory: document.getElementById("menuRelicInventory"),
    runHud: document.getElementById("runHud"),
    debugPanel: document.getElementById("debugPanel"),
    debugStats: document.getElementById("debugStats"),
    menuQpHud: document.getElementById("menuQpHud"),
    menuTree: document.getElementById("menuTree"),
    menuQuests: document.getElementById("menuQuests"),
    levelUp: document.getElementById("levelUp"),
    choices: document.getElementById("choices"),
    relicChoice: document.getElementById("relicChoice"),
    relicChoiceTitle: document.getElementById("relicChoiceTitle"),
    relicChoiceText: document.getElementById("relicChoiceText"),
    relicChoices: document.getElementById("relicChoices"),
    endScreen: document.getElementById("endScreen"),
    runStats: document.getElementById("runStats"),
    closeEnd: document.getElementById("closeEnd"),
    closeEndX: document.getElementById("closeEndX"),
  };
}

function createUiRenderer({
  ui,
  weaponDefs,
  weaponUnlocks,
  upgradeDefs,
  questDefs,
  getSave,
  getUpgradeTier,
  hasNode,
  isNodeVisible,
  isQuestComplete,
  nodeGateStatus,
  buyWeaponUnlock,
  buyUpgrade,
}) {
  return globalThis.TapSurvivorUiProgression.createUiProgressionRenderer({
    ui,
    weaponDefs,
    weaponUnlocks,
    upgradeDefs,
    questDefs,
    getSave,
    getUpgradeTier,
    hasNode,
    isNodeVisible,
    isQuestComplete,
    nodeGateStatus,
    buyWeaponUnlock,
    buyUpgrade,
  });
}

globalThis.TapSurvivorUi = {
  createUi,
  createUiRenderer,
};
})();
